1. Strassen's Matrix Multiplication

In [3]:
## Implementation of strassen's matrix multiplication
## Recurrence relation: 7T(n/2) + n^2
## Using master's theorem, O(n^2.81)
## Approach - using divide and conquer
import numpy as np

def split(matrix):
    row, col = matrix.shape
    row2, col2 = row//2, col//2
    return matrix[:row2, :col2], matrix[:row2, col2:], matrix[row2:, :col2], matrix[row2:, col2:]

def strassen(x, y):
    # Base case when size of matrices is 1x1
    if len(x) == 1:
        return x * y

    # Splitting the matrices into quadrants. This will be done recursively
    # until the base case is reached.
    a, b, c, d = split(x)
    e, f, g, h = split(y)

    # Computing the 7 products, recursively (p1, p2...p7)
    p1 = strassen(a, f - h)
    p2 = strassen(a + b, h)
    p3 = strassen(c + d, e)
    p4 = strassen(d, g - e)
    p5 = strassen(a + d, e + h)
    p6 = strassen(b - d, g + h)
    p7 = strassen(a - c, e + f)

    # Computing the values of the 4 quadrants of the final matrix c
    c11 = p5 + p4 - p2 + p6
    c12 = p1 + p2
    c21 = p3 + p4
    c22 = p1 + p5 - p3 - p7

    # Combining the 4 quadrants into a single matrix by stacking horizontally and vertically.
    c = np.vstack((np.hstack((c11, c12)), np.hstack((c21, c22))))

    return c

## Driver code
A = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [2, 2, 2, 2]])
B = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [2, 2, 2, 2]])
print('Matrix multiplication result: ')
print(strassen(A, B))

Matrix multiplication result: 
[[ 8  8  8  8]
 [16 16 16 16]
 [24 24 24 24]
 [16 16 16 16]]


2. Median of two arrays

**Approach 1**

In [3]:
def findMedianSortedArrays(nums1, nums2):
  nums = sorted(nums1 + nums2)
  n = len(nums)
  if n % 2 == 0:
    mid = n//2
    return (nums[mid] + nums[mid-1]) / 2
  else:
    return nums[n//2]

## Driver code
nums1 = [1, 2]
nums2 = [3, 4]
result = findMedianSortedArrays(nums1, nums2)
print(result)

2.5


**Approach 2**

In [4]:
import sys
from typing import List


def findMedianSortedArrays(nums1: List[int], nums2: List[int]) -> float:
    if len(nums1) > len(nums2):
        nums1, nums2 = nums2, nums1
  
    m = len(nums1)
    n = len(nums2)
 
    start = 0
    end = m
    
    while start <= end:
        
        partition_nums1 = (start + end) // 2
        partition_nums2 = (m + n + 1) // 2 - partition_nums1
        
        maxLeftNums1 = -sys.maxsize if partition_nums1 == 0 else nums1[partition_nums1 - 1]
        minRightNums1 = sys.maxsize if partition_nums1 == m else nums1[partition_nums1]
        
        maxLeftNums2 = -sys.maxsize if partition_nums2 == 0 else nums2[partition_nums2 - 1]
        minRightNums2 = sys.maxsize if partition_nums2 == n else nums2[partition_nums2]
        if maxLeftNums1 <= minRightNums2 and maxLeftNums2 <= minRightNums1:
            if (m + n) % 2 == 0:
                return (max(maxLeftNums1, maxLeftNums2) + min(minRightNums1, minRightNums2)) / 2
            else:
                return max(maxLeftNums1, maxLeftNums2)
        elif maxLeftNums1 > minRightNums2:
            end = partition_nums1 - 1
        else:
            start = partition_nums1 + 1
    raise Exception("IllegalArgumentException")


## Driver code
nums1 = [1, 2]
nums2 = [3, 4]
findMedianSortedArrays(nums1, nums2)

2.5

3. Power of an Element

In [2]:
def myPow(x, n):
  if n == 0:
    return 1
  ## this is the major logic
  elif n < 0:
    x = 1/x
    n = -n
    return myPow(x, n)
  elif n == 1:
    return x
  else:
    ## Divide
    mid = n // 2
    ## conquer
    b = myPow(x, mid)
    result = b * b
    ## combine
    if n % 2 == 0:
      return result
    else:
      return result * x

## Driver code
x = 2.00000
n = -2
result = myPow(x, n)
print(result)

0.25


4. Dividing two integers without using division, multiplication and mod operator

Concept of Bit Manipulation required -> 
Indepth discussion will be done on next live class on Friday

5. Count of number of inversions

In [11]:
# Function to Use Inversion Count
def mergeSort(arr, n):
	# A temp_arr is created to store
	# sorted array in merge function
	temp_arr = [0]*n
	return helper(arr, temp_arr, 0, n-1)


def helper(arr, temp_arr, left, right):

	inv_count = 0

	if left < right:

		mid = (left + right)//2

    ## Left subtree inversion count
		inv_count += helper(arr, temp_arr,
								left, mid)
    ## Right subtree inversion count
		inv_count += helper(arr, temp_arr,
								mid + 1, right)

    ## after merge/combine inversion count
		inv_count += mergeProcedure(arr, temp_arr, left, mid, right)
	return inv_count


def mergeProcedure(arr, temp_arr, left, mid, right):
	i = left	 # Starting index of left subarray
	j = mid + 1 # Starting index of right subarray
	k = left	 # Starting index of to be sorted subarray
	inv_count = 0

	# Conditions are checked to make sure that
	# i and j don't exceed their
	# subarray limits.

	while i <= mid and j <= right:

		# There will be no inversion if arr[i] <= arr[j]
		if arr[i] <= arr[j]:
			temp_arr[k] = arr[i]
			k += 1
			i += 1
		else:
			# Inversion will occur.
			temp_arr[k] = arr[j]
			inv_count += (mid-i + 1)
			k += 1
			j += 1

	# Copy the remaining elements of left
	# subarray into temporary array
	while i <= mid:
		temp_arr[k] = arr[i]
		k += 1
		i += 1

	# Copy the remaining elements of right
	# subarray into temporary array
	while j <= right:
		temp_arr[k] = arr[j]
		k += 1
		j += 1

	# Copy the sorted subarray into Original array
	for i in range(left, right + 1):
		arr[i] = temp_arr[i]

	return inv_count


# Driver Code
arr = [70, 50, 60, 10, 20, 30, 80, 15]
n = len(arr)
result = mergeSort(arr, n)
print("Number of inversions are", result)

Number of inversions are 17
